#!/usr/bin/env bash
# PreToolUse hook: Block edits to auto-generated files (requirements.txt)
# Reads JSON from stdin, extracts file_path, blocks if requirements.txt

set -euo pipefail

# Read JSON payload from stdin
INPUT=$(cat)

# Extract file_path from tool_input using python3 (guaranteed available)
FILE_PATH=$(python3 -c "
import json, sys
data = json.loads(sys.argv[1])
print(data.get('tool_input', {}).get('file_path', ''))
" "$INPUT" 2>/dev/null) || exit 0

# Block edits to requirements.txt
if [[ "$FILE_PATH" == */requirements.txt || "$FILE_PATH" == "requirements.txt" ]]; then
    echo '{"decision":"block","reason":"requirements.txt is auto-generated by uv export. Use mise run deps:add instead."}'
    exit 2
fi

exit 0
