import os
import time

from python.helpers import files
from python.helpers.extension import Extension


class adr_generator(Extension):
    """
    Automated ADR Generator.
    Triggers at the end of a monologue to detect and record technical decisions.
    """

    async def execute(self, **kwargs) -> None:
        if not self.agent: return

        # We only care about success or completion
        history = self.agent.history.get_history()
        if not history: return

        last_ai_msg = ""
        for msg in reversed(history):
            if msg.role == "assistant":
                last_ai_msg = msg.content
                break

        keywords = ["architecture", "decision", "choice", "pattern", "design", "workflow"]
        if not any(kw in last_ai_msg.lower() for kw in keywords):
            return

        try:
            project_name = getattr(self.agent, "agent_name", "Unknown Agent")
            adr_dir = files.get_abs_path("knowledge/custom/architectural_patterns/adrs")
            os.makedirs(adr_dir, exist_ok=True)

            timestamp = int(time.time())
            filename = f"ADR-{timestamp}.md"
            filepath = os.path.join(adr_dir, filename)

            adr_content = f"""# ADR: {timestamp} - {project_name} Decision

## Status
Proposed

## Context
Decided during session focusing on solutioning.

## Decision
The agent processed a task involving: "{last_ai_msg[:200]}..."

## Consequences
- Recorded in automated knowledge base.
- Available for future RAG retrieval.

---
*Generated by Automated ADR Extension*
"""
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(adr_content)

        except Exception:
            pass # Silent fail to not disrupt main loop
