version: "3.8"

services:
  agent0:
    image: agent0ai/agent-zero:latest
    container_name: agent0
    restart: unless-stopped
    ports:
      - "${HOST_IP}:8443:80"
      - "80:80"
#      - "50022:22"
    volumes:
      - ./data:/a0/data
      - ./usr:/a0/usr
    env_file:
      - ./data/.env
    security_opt:
      - seccomp:unconfined
