version: '3.8'

services:
  agent-zero:
    build:
      context: ..
      dockerfile: DockerfileLocal
    ports:
      - "${A0_DOCKER_HTTP_PORT:-55080}:80"  # Web UI
      - "${A0_DOCKER_SSH_PORT:-55022}:22"      # SSH access
    volumes:
      - a0:/a0
      - root:/root
    container_name: ${A0_DOCKER_CONTAINER_NAME:-agent-zero}
    environment:
      # Core Model Configuration
      - A0_SET_CHAT_MODEL_PROVIDER=${A0_SET_CHAT_MODEL_PROVIDER:-openrouter}
      - A0_SET_CHAT_MODEL_NAME=${A0_SET_CHAT_MODEL_NAME:-openai/gpt-4.1}
      - A0_SET_CHAT_MODEL_API_BASE=${A0_SET_CHAT_MODEL_API_BASE:-}
      - A0_SET_CHAT_MODEL_CTX_LENGTH=${A0_SET_CHAT_MODEL_CTX_LENGTH:-100000}
      - A0_SET_CHAT_MODEL_CTX_HISTORY=${A0_SET_CHAT_MODEL_CTX_HISTORY:-0.7}
      - A0_SET_CHAT_MODEL_VISION=${A0_SET_CHAT_MODEL_VISION:-true}
      - A0_SET_CHAT_MODEL_RL_REQUESTS=${A0_SET_CHAT_MODEL_RL_REQUESTS:-0}
      - A0_SET_CHAT_MODEL_RL_INPUT=${A0_SET_CHAT_MODEL_RL_INPUT:-0}
      - A0_SET_CHAT_MODEL_RL_OUTPUT=${A0_SET_CHAT_MODEL_RL_OUTPUT:-0}
      - A0_SET_CHAT_MODEL_KWARGS_TEMPERATURE=${A0_SET_CHAT_MODEL_KWARGS_TEMPERATURE:-0}

      # Utility Model Configuration
      - A0_SET_UTIL_MODEL_PROVIDER=${A0_SET_UTIL_MODEL_PROVIDER:-openrouter}
      - A0_SET_UTIL_MODEL_NAME=${A0_SET_UTIL_MODEL_NAME:-openai/gpt-4.1-mini}
      - A0_SET_UTIL_MODEL_API_BASE=${A0_SET_UTIL_MODEL_API_BASE:-}
      - A0_SET_UTIL_MODEL_CTX_LENGTH=${A0_SET_UTIL_MODEL_CTX_LENGTH:-100000}
      - A0_SET_UTIL_MODEL_CTX_INPUT=${A0_SET_UTIL_MODEL_CTX_INPUT:-0.7}
      - A0_SET_UTIL_MODEL_RL_REQUESTS=${A0_SET_UTIL_MODEL_RL_REQUESTS:-0}
      - A0_SET_UTIL_MODEL_RL_INPUT=${A0_SET_UTIL_MODEL_RL_INPUT:-0}
      - A0_SET_UTIL_MODEL_RL_OUTPUT=${A0_SET_UTIL_MODEL_RL_OUTPUT:-0}
      - A0_SET_UTIL_MODEL_KWARGS_TEMPERATURE=${A0_SET_UTIL_MODEL_KWARGS_TEMPERATURE:-0}

      # Embedding Model Configuration
      - A0_SET_EMBED_MODEL_PROVIDER=${A0_SET_EMBED_MODEL_PROVIDER:-huggingface}
      - A0_SET_EMBED_MODEL_NAME=${A0_SET_EMBED_MODEL_NAME:-sentence-transformers/all-MiniLM-L6-v2}
      - A0_SET_EMBED_MODEL_API_BASE=${A0_SET_EMBED_MODEL_API_BASE:-}
      - A0_SET_EMBED_MODEL_RL_REQUESTS=${A0_SET_EMBED_MODEL_RL_REQUESTS:-0}
      - A0_SET_EMBED_MODEL_RL_INPUT=${A0_SET_EMBED_MODEL_RL_INPUT:-0}

      # Browser Model Configuration
      - A0_SET_BROWSER_MODEL_PROVIDER=${A0_SET_BROWSER_MODEL_PROVIDER:-openrouter}
      - A0_SET_BROWSER_MODEL_NAME=${A0_SET_BROWSER_MODEL_NAME:-openai/gpt-4.1}
      - A0_SET_BROWSER_MODEL_API_BASE=${A0_SET_BROWSER_MODEL_API_BASE:-}
      - A0_SET_BROWSER_MODEL_VISION=${A0_SET_BROWSER_MODEL_VISION:-true}
      - A0_SET_BROWSER_MODEL_RL_REQUESTS=${A0_SET_BROWSER_MODEL_RL_REQUESTS:-0}
      - A0_SET_BROWSER_MODEL_RL_INPUT=${A0_SET_BROWSER_MODEL_RL_INPUT:-0}
      - A0_SET_BROWSER_MODEL_RL_OUTPUT=${A0_SET_BROWSER_MODEL_RL_OUTPUT:-0}
      - A0_SET_BROWSER_MODEL_KWARGS_TEMPERATURE=${A0_SET_BROWSER_MODEL_KWARGS_TEMPERATURE:-0}

      # Memory System Configuration
      - A0_SET_MEMORY_RECALL_ENABLED=${A0_SET_MEMORY_RECALL_ENABLED:-true}
      - A0_SET_MEMORY_RECALL_DELAYED=${A0_SET_MEMORY_RECALL_DELAYED:-false}
      - A0_SET_MEMORY_RECALL_INTERVAL=${A0_SET_MEMORY_RECALL_INTERVAL:-3}
      - A0_SET_MEMORY_RECALL_HISTORY_LEN=${A0_SET_MEMORY_RECALL_HISTORY_LEN:-10000}
      - A0_SET_MEMORY_RECALL_MEMORIES_MAX_SEARCH=${A0_SET_MEMORY_RECALL_MEMORIES_MAX_SEARCH:-12}
      - A0_SET_MEMORY_RECALL_SOLUTIONS_MAX_SEARCH=${A0_SET_MEMORY_RECALL_SOLUTIONS_MAX_SEARCH:-8}
      - A0_SET_MEMORY_RECALL_MEMORIES_MAX_RESULT=${A0_SET_MEMORY_RECALL_MEMORIES_MAX_RESULT:-5}
      - A0_SET_MEMORY_RECALL_SOLUTIONS_MAX_RESULT=${A0_SET_MEMORY_RECALL_SOLUTIONS_MAX_RESULT:-3}
      - A0_SET_MEMORY_RECALL_SIMILARITY_THRESHOLD=${A0_SET_MEMORY_RECALL_SIMILARITY_THRESHOLD:-0.7}
      - A0_SET_MEMORY_RECALL_QUERY_PREP=${A0_SET_MEMORY_RECALL_QUERY_PREP:-true}
      - A0_SET_MEMORY_RECALL_POST_FILTER=${A0_SET_MEMORY_RECALL_POST_FILTER:-true}
      - A0_SET_MEMORY_MEMORIZE_ENABLED=${A0_SET_MEMORY_MEMORIZE_ENABLED:-true}
      - A0_SET_MEMORY_MEMORIZE_CONSOLIDATION=${A0_SET_MEMORY_MEMORIZE_CONSOLIDATION:-true}
      - A0_SET_MEMORY_MEMORIZE_REPLACE_THRESHOLD=${A0_SET_MEMORY_MEMORIZE_REPLACE_THRESHOLD:-0.9}

      # Authentication & Security
      - A0_SET_AUTH_LOGIN=${A0_SET_AUTH_LOGIN:-}
      - A0_SET_AUTH_PASSWORD=${A0_SET_AUTH_PASSWORD:-}
      - A0_ROOT_PASSWORD=${A0_ROOT_PASSWORD:-}
      - A0_RFC_PASSWORD=${A0_RFC_PASSWORD:-}

      # Agent Configuration
      - A0_SET_AGENT_PROFILE=${A0_SET_AGENT_PROFILE:-agent0}
      - A0_SET_AGENT_MEMORY_SUBDIR=${A0_SET_AGENT_MEMORY_SUBDIR:-default}
      - A0_SET_AGENT_KNOWLEDGE_SUBDIR=${A0_SET_AGENT_KNOWLEDGE_SUBDIR:-custom}

      # Remote Function Calls
      - A0_SET_RFC_AUTO_DOCKER=${A0_SET_RFC_AUTO_DOCKER:-true}
      - A0_SET_RFC_URL=${A0_SET_RFC_URL:-localhost}
      - A0_SET_RFC_PORT_HTTP=${A0_SET_RFC_PORT_HTTP:-55080}
      - A0_SET_RFC_PORT_SSH=${A0_SET_RFC_PORT_SSH:-55022}

      # Speech Configuration
      - A0_SET_STT_MODEL_SIZE=${A0_SET_STT_MODEL_SIZE:-base}
      - A0_SET_STT_LANGUAGE=${A0_SET_STT_LANGUAGE:-en}
      - A0_SET_STT_SILENCE_THRESHOLD=${A0_SET_STT_SILENCE_THRESHOLD:-0.3}
      - A0_SET_STT_SILENCE_DURATION=${A0_SET_STT_SILENCE_DURATION:-1000}
      - A0_SET_STT_WAITING_TIMEOUT=${A0_SET_STT_WAITING_TIMEOUT:-2000}
      - A0_SET_TTS_KOKORO=${A0_SET_TTS_KOKORO:-true}

      # MCP Configuration
      - A0_SET_MCP_CLIENT_INIT_TIMEOUT=${A0_SET_MCP_CLIENT_INIT_TIMEOUT:-10}
      - A0_SET_MCP_CLIENT_TOOL_TIMEOUT=${A0_SET_MCP_CLIENT_TOOL_TIMEOUT:-120}
      - A0_SET_MCP_SERVER_ENABLED=${A0_SET_MCP_SERVER_ENABLED:-false}
      - A0_SET_A2A_SERVER_ENABLED=${A0_SET_A2A_SERVER_ENABLED:-false}

      # API Keys (set your keys here)
      - A0_SET_API_KEY_ANTHROPIC=${A0_SET_API_KEY_ANTHROPIC:-}
      - A0_SET_API_KEY_DEEPSEEK=${A0_SET_API_KEY_DEEPSEEK:-}
      - A0_SET_API_KEY_GOOGLE=${A0_SET_API_KEY_GOOGLE:-}
      - A0_SET_API_KEY_GROQ=${A0_SET_API_KEY_GROQ:-}
      - A0_SET_API_KEY_HUGGINGFACE=${A0_SET_API_KEY_HUGGINGFACE:-}
      - A0_SET_API_KEY_LM_STUDIO=${A0_SET_API_KEY_LM_STUDIO:-}
      - A0_SET_API_KEY_MISTRAL=${A0_SET_API_KEY_MISTRAL:-}
      - A0_SET_API_KEY_OLLAMA=${A0_SET_API_KEY_OLLAMA:-}
      - A0_SET_API_KEY_OPENAI=${A0_SET_API_KEY_OPENAI:-}
      - A0_SET_API_KEY_AZURE=${A0_SET_API_KEY_AZURE:-}
      - A0_SET_API_KEY_OPENROUTER=${A0_SET_API_KEY_OPENROUTER:-}
      - A0_SET_API_KEY_SAMBANOVA=${A0_SET_API_KEY_SAMBANOVA:-}
      - A0_SET_API_KEY_VENICE=${A0_SET_API_KEY_VENICE:-}
      - A0_SET_API_KEY_OTHER=${A0_SET_API_KEY_OTHER:-}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    # Additional configuration as needed

volumes:
  root:
    driver: local
  a0:
    driver: local
