version: "3.9"
services:
  agentzero-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - GA_KEY_JSON=${GA_KEY_JSON}
      - DATABASE_URL=postgresql+asyncpg://agent:pass@postgres:5432/agent

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: agent
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
